# This workflow is used to trigger the "PR Review Comment" workflow. This chaining is needed
# because workflows triggered by pull_request_review_comment do not have access to secrets.

name: PR Review Comment Trigger
on:
  pull_request_review_comment:
    types:
      - created

jobs:
  trigger:
    runs-on: ubuntu-latest

    # The "PR Review Comment" workflow will check the success status of this workflow and only mark
    # the PR for re-review if this workflow was successful, which is when the author leaves a review comment.
    if: github.repository == 'backstage/backstage' && github.event.comment.user.id == github.event.pull_request.user.id

    steps:
      - run: echo "This PR needs another review"
